version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: pytest
      - dependency-name: pytest-homeassistant-custom-component
      - dependency-name: homeassistant
      - dependency-name: home-assistant-frontend
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
